# Generated by Django 5.0.4 on 2024-06-19 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0035_client_contact_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPermissions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permissions", models.CharField(max_length=100)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="backend.team")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_perms", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
